spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: market
    password: market
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop